services:
  - type: web
    name: rag-ai-chatbot
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app --timeout 600

    envVars:
      - key: GROQ_API_KEY
        sync: false
