services:
  - type: web
    name: rag-ai-chatbot
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app --workers 2 --timeout 120 --graceful-timeout 30

    envVars:
      - key: GROQ_API_KEY
        sync: false
